version: "3.5"

services:
  devtool-api:
    image: registry.cn-shanghai.aliyuncs.com/iyjianwc/devtool-api
    restart: always
    env_file:
      - .env
    command: node dist/main.js
    depends_on:
      - redis
      - mysql
  devtool-ui:
    image: registry.cn-shanghai.aliyuncs.com/iyjianwc/devtool-ui
    restart: always
    env_file:
      - .env    
    ports:
      - 54321:3000
  redis:
    image: redis
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devtool
      MYSQL_USER: devtool
      MYSQL_PASSWORD: devtool
